// LOCALHOST
### Get all contacts
GET http://localhost:3000/contacts


### Get contact by id
GET http://localhost:3000/contacts/622023f642f9ab4cd6e060b3


### Create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Rain",
    "lastName": "Ng",
    "email": "test@example.com",
    "favoriteColor": "Yellow",
    "birthady": "Sep"
}

### PUT contact
PUT http://localhost:3000/users/672f689120130c10661425a8 HTTP/1.1

{
    "firstName": "Rain",
    "lastName": "Ng",
    "email": "test@example.com",
    "favoriteColor": "Yellow",
    "birthady": "Sep"
}

### DELETE contact
DELETE http://localhost:3000/users/672f689120130c10661425a8 HTTP/1.1