// LOCALHOST
### Get all contacts
GET https://project1-8xqo.onrender.com/contacts


### Get contact by id
GET https://project1-8xqo.onrender.com/contacts/674f105ba2f812dc6a701f6c


### Create contact
POST https://project1-8xqo.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Rain",
    "lastName": "Ng",
    "email": "RainNg@gmail.com",
    "favoriteColor": "Yellow",
    "birthady": "Sep 2, 1996"
}

### PUT contact
PUT https://project1-8xqo.onrender.com/contacts/674f10c5a2f812dc6a701f6d HTTP/1.1

{
    "firstName": "Rain",
    "lastName": "Ng",
    "email": "RainNg@gmail.com",
    "favoriteColor": "Yellow",
    "birthady": "Sep 2, 1996"
}

### DELETE contact
DELETE http://localhost:3001/contacts/674bf5ea44a7368301f12881 HTTP/1.1